sudo: required

services:
  - 'docker'

before_install:
  - docker build -t jzhu1224/nestjs-starter .

script:
  - docker run jzhu1224/nestjs-starter

deploy:
  provider: elasticbeanstalk
  access_key_id: 'AKIAUBZNSC72TACVPHOD'
  secret_access_key:
    secure: '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'
  region: 'ap-southeast-2'
  app: 'hello'
  env: 'hello-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-278731560949'
  on:
    branch: master
